name: BlogPilot
favicon: null
layout_spectrum: 0.538596437079832
typography_spectrum: 0.8465994393918663
title: BlogPilot!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13223434565588832
  lightness: 0.3878914031665772
  saturation: 0.48426215164363384
  rhythmicContrast: 0.18703367467969656
purpose: []
