name: BlogPilot
favicon: null
layout_spectrum: 0.25572
typography_spectrum: 0.17273
title: BlogPilot!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
